userlogin/userapp/urls.py
from django.urls import path
from userapp import views

app_name = 'userapp'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

userlogin/userlogin/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from userapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('userapp/',include('userapp.urls')),
    path('logout/',views.user_logout,name='logout'),
]

userlogin/userapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    profile_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

userlogin/userapp/views.py
from django.shortcuts import render
from userapp.myform import UserForm,UserInfoForm
from userapp.models import UserProfileInfo
# Create your views here.

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,authenticate,logout


def index(request):
    return render(request,'userapp/index.html')

def register(request):

# registered variable for if the form is registered or not.
    registered = False
# if we got the POST request means the user wants to save the data.
    if request.method == "POST":
# grab the data from both the forms
        user_info = UserForm(request.POST)
        profile_info = UserInfoForm(request.POST)
# check if both the forms are valid or not
        if user_info.is_valid() and profile_info.is_valid():
# save intially what data was posted
            user = user_info.save()
# save the password as hash
            user.set_password(user.password)
# save the password hash to the model
            user.save()
# we have set the commit to false as we dont want to make the collision with the other form data
            profile = profile_info.save(commit=False)
# what we created one to one relationship, we are creating the same in the views file also
            profile.user = user
# We have to check weather we have any profile pic in the post request if so than we grab that and save it ot the model
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
# save the profile form data
            profile.save()
# At last the form is registered
            registered = True
# the else part shows if the form is not registered than errors are occured
        else:
            print(user_info.errors,profile_info.errors)
# This else part is for if the request is just an http request so we just display the forms
    else:
        user_info = UserForm()
        profile_info = UserInfoForm()

    return render(request,'userapp/register.html',{
                            'user_info':user_info,
                            'profile_info':profile_info,
                            'registered':registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def  user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account is not Active")

        else:
            print("Login Failed.Please try again!!!")
            print("username:{} password:{}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request,'userapp/login.html',{})

userlogin/templates/userapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
      <nav class="navbar navbar-light navbar-expand-md" style="background-color: #e3f2fd;' class="d-md-flex p-2 flex-md-fill bd-highlight">
      <div class="container">
        <ul class='navbar-nav mr-auto'>
          <li><a class='navbar-brand' href="{% url 'index' %}">Django</a></li>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="d-md-flex p-2 flex-fill bd-highlight align-items-center">
          <li class='navbar-item'><a class='navbar-link' href="{% url 'userapp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
              <li class='navbar-item'><a class='navbar-link' href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li class='navbar-item'><a class='navbar-link' href="{% url 'userapp:user_login' %}">Log In</a></li>
          {% endif %}
        </div>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

userlogin/templates/userapp/index.html
<!DOCTYPE html>
{% extends "userapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to the Home Page.</h1>
</div>

{% endblock %}

userlogin/templates/userapp/login.html
{% extends "userapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login:</h1>
    <form action="{% url 'userapp:user_login' %}" method="post">

      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="Password:">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>
</div>

{% endblock %}

userlogin/templates/userapp/register.html
<!DOCTYPE html>
{%extends 'userapp/base.html' %}
{% load static %}
  {% block body_block %}

    <h1 class="row justify-content-center align-items-center">Welcome to Registration Page.</h1>
    <div class="jumbotron">
      {% if registered %}
        <h1>Thanks for Registration.</h1>
      {% else %}
        <h3>Fill up the Registration Form.</h3><br>

        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {{ user_info.as_p }}
          {{ profile_info.as_p }}
          <input type="submit" value="Register">
        </form>
      {% endif %}
    </div>

  {% endblock %}